# Generated by Django 5.1.3 on 2024-11-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
