# Generated by Django 5.1.3 on 2024-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('series_or_movie', models.CharField(max_length=50)),
                ('hidden_gem_score', models.FloatField(blank=True, null=True)),
                ('country_availability', models.TextField()),
                ('runtime', models.CharField(max_length=50)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('imdb_score', models.FloatField(blank=True, null=True)),
                ('awards_received', models.IntegerField(blank=True, null=True)),
                ('awards_nominated_for', models.IntegerField(blank=True, null=True)),
                ('boxoffice', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('netflix_link', models.URLField(blank=True, null=True)),
                ('imdb_link', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
